### ISSUE TITLE
Use realpath instead of normpath to check presence in path

### ISSUE THREAD

**Issue by FallenWarrior2k** [ofek/userpath#22]
The functionality to test if a location is on the path currently relies on normpath, as can be seen [here](https://github.com/ofek/userpath/blob/master/userpath/utils.py#L17).

However, normpath is not symlink-aware. This means that if a symlink to a directory is on the path, `userpath` will report that the actual location of that directory is not on the path, which can cause issues like pipxproject/pipx#329.

**Comment by ofek** [comment]
https://pypi.org/project/userpath/1.7.0/
