### ISSUE TITLE
[Win] doesn't work with python from MS Store

### ISSUE THREAD

**Issue by imba-tjd** [ofek/userpath#25]
![图片](https://user-images.githubusercontent.com/24759802/83937720-d4645400-a801-11ea-8ac4-cbbc49a4a7e2.png)

Have rebooted.

```
> userpath append C:\Users\xxx\.local\bin
The directory `C:\Users\xxx\.local\bin` is already in PATH, pending a shell restart! If you are sure you want to proceed, try again with the -f/--force flag.

> userpath append C:\Users\xxx\.local\bin -f
Success!

> ls C:\Users\xxx\.local\bin
iptest.exe  iptest3.exe  ipython.exe  ipython3.exe

> userpath verify C:\Users\xxx\.local\bin
The directory `C:\Users\xxx\.local\bin` is in PATH, pending a shell restart!

> ipython
'ipython' is not recognized as an internal or external command,
operable program or batch file.

> echo %path%
C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MacType;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\xxx\AppData\Local\Programs\Python\Launcher\;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\bin;C:\Users\xxx\.dotnet\tools;C:\Users\xxx\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn;C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64;C:\mingw64\bin;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts;C:\tools;C:\Program Files\LLVM\bin;C:\Program Files\heroku\bin;C:\Users\xxx\.dotnet\tools;
```

**Comment by ofek** [comment]
Did you restart your shell?

**Comment by imba-tjd** [comment]
I have tested python from python.org and it works. So I think it's the limitation from MS Store. Don't know whether this could be fixed.

**Comment by ofek** [comment]
Can you please try restarting your shell?

**Comment by imba-tjd** [comment]
I had said that I have rebooted.

**Comment by ofek** [comment]
What shell are you using?

**Comment by imba-tjd** [comment]
cmd and powershell and pwsh. The 1st floor is cmd.

**Comment by ofek** [comment]
Ah! So you tried this with nested shells?

**Comment by imba-tjd** [comment]
no…… I test this with different shells.

**Comment by ofek** [comment]
Now that you've restarted can I see your PATH once more?

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/83956438-ab3ed480-a890-11ea-9c54-9f96c0f97047.png)

```
> echo %path%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MacType;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\xxx\AppData\Local\Programs\Python\Launcher\;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\bin;C:\Users\xxx\.dotnet\tools;C:\Users\xxx\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn;C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64;C:\mingw64\bin;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\tools;C:\Program Files\LLVM\bin;C:\Program Files\heroku\bin;C:\Users\xxx\.dotnet\tools;
```

**Comment by ofek** [comment]
Can you try:

```
powershell -Command "& {[Environment]::GetEnvironmentVariable('PATH', 'User')}"
```

**Comment by imba-tjd** [comment]
I removed some unused and duplicated entries. Of course `userpath verify C:\Users\xxx\.local\bin` still shows "The directory is in PATH".

Current:

![图片](https://user-images.githubusercontent.com/24759802/83957297-9adf2780-a899-11ea-8440-9cf00f9e6cbb.png)

Powershell:

```
PS C:\Users\xxx> & {[Environment]::GetEnvironmentVariable('PATH', 'User')}
C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn;C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64;C:\mingw64\bin;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\tools;C:\Program Files\LLVM\bin;C:\Program Files\heroku\bin;C:\Users\xxx\.dotnet\tools;
```

cmd:

```
> echo %path%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MacType;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn;C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64;C:\mingw64\bin;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\tools;C:\Program Files\LLVM\bin;C:\Program Files\heroku\bin;C:\Users\xxx\.dotnet\tools;
```

**Comment by ofek** [comment]
I'm extremely confused. I'll have to think about this.

**Comment by DataGhost** [comment]
I'm having the same issue, also with the Windows Store version. It did not even occur to me, but recent experiences with Windows Store apps (trying to modify them etc) lead me to some sources saying that the whole Store business executes in some kind of sandbox somehow. It does end up in the registry (which I can only assume is virtual, since searching with regedit did not yield any results) but does not appear to end up in any working environment.

Starting the python interpreter from the commandline seems to supply it with the environment of the commandline (logical) so it does not load the Environment key from the virtual registry. Querying, however, yields:

```
>>> with winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Environment', 0, winreg.KEY_READ) as key:
...     print(winreg.QueryValueEx(key, 'PATH'))
...
('%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\Username\\.local\\bin', 2)
>>> os.environ.get("PATH", "")
'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\Username\\AppData\\Local\\Microsoft\\WindowsApps;'
```

So userpath thinks all is correct but it'll never go live. I'm not sure this is fixable other than manually installing and updating Python, which kind of defeats the purpose of the store.

**Comment by ofek** [comment]
Found this: https://docs.python.org/3/using/windows.html#known-issues

Unfortunately, nothing can be done I think.

**Comment by DataGhost** [comment]
Well, I just hacked up an ugly workaround. Reads are from the normal registry, writes go to a private copy so that's when they start to go out of sync. It is possible to use `subprocess` to invoke something like `reg add HKCU\Environment /v PATH /t REG_EXPAND_SZ /d new_path`. I just verified that this writes to the public registry.

**Comment by ofek** [comment]
@DataGhost If you come up with a way to detect Store Python I'll do this

**Comment by DataGhost** [comment]
```
>>> import sys
>>> sys.executable
'C:\\Users\\Username\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\python.exe'
```
This is a user-specific path, but will always have the WindowsApps component. Something like this should work:
```
>>> def is_store():
...     import sys
...     return r"\AppData\Local\Microsoft\WindowsApps\" in sys.executable
...
>>> is_store()
True
```
and returns False on another machine where I have the non-store version. Although I'd say this could/should be fixed by modifying the winreg API to use these calls on Store versions but umm I doubt they're going to like the suggestion.

**Comment by ofek** [comment]
Thanks! One more question: does invoking userpath as subprocess work? It would be easier to call itself (with env var to prevent fork bomb)

**Comment by DataGhost** [comment]
I'm unsure what you mean or what you're trying to achieve by calling it in a subprocess. I'm not using userpath directly, I only saw that installing pipx and then running pipx ensurepath (which invoked userpath) didn't seem to have any effect. As long as the main executable lives in the WindowsApps directory, it seems to execute inside this sandbox-like thing. The def I just posted isn't flawless though. I just tried it in a virtualenv which has a stub binary in another location (`...\venvname\Scripts\python.exe`) and it does not write to the registry (using `winreg`) even though `is_store()` returned `False`.

**Comment by ofek** [comment]
Thank you, I'll fix tomorrow

**Comment by Kurt-von-Laven** [comment]
Has this issue already been fixed, or no?

**Comment by ofek** [comment]
No, I haven't had time. Feel free to make a PR 🙂

**Comment by Kurt-von-Laven** [comment]
Sorry, but this issue would take me a disproportionate amount of time to fix relative to its value in light of my own ignorance of Windows. I am not sure if this is the right approach, but I am presently calling `set "PATH=%PATH%;%USERPROFILE%\.local\bin"` from a .bat script as a workaround for the fact that `pipx ensurepath` isn't working as intended.

**Comment by imba-tjd** [comment]
@ofek Hi. Do you consider to rewrite the logic to use `setx.exe` to modify PATH?

For example `setx PATH "%PATH%;<newpath>"` will permanently change PATH.

**Comment by imba-tjd** [comment]
Well, I just tested again. Surprisingly it works. I don't know whether it's because now I'm using 3.10 or Win11.

**Comment by ofek** [comment]
Huh, maybe Win11?

**Comment by imba-tjd** [comment]
I tried 3.11b4 from Store on Win10 1903 and it works.
