### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by FFY00** [ofek/userpath#26]
Seems like 1.4.0 is out but there is not git tag.

**Comment by FFY00** [comment]
Can someone push the missing git tags? I am packaging userpath for Arch Linux and would really appreciate if they were available.

**Comment by kapsh** [comment]
I second this request. @ofek please?

**Comment by ofek** [comment]
Pushed, sorry!

**Comment by FFY00** [comment]
No worries, thank you so much :blush:

**Comment by FFY00** [comment]
Looks like there is also 1.4.1, could you also tag it? Thanks!

**Comment by ofek** [comment]
Done!

**Comment by kapsh** [comment]
@ofek thanks for resolve.
