### ISSUE TITLE
Raise `WM_SETTINGCHANGE` after setting environment registry keys on Windows

### ISSUE THREAD

**Issue by TBBle** [ofek/userpath#40]
This is a feature request to resolve issues seen in https://github.com/pypa/pipx/issues/659, where after `pipx ensurepath` (implemented using this library), you must either log-out-and-in, or manually edit an env-var (both the env-var editor UI and `setx` appear to raise this message after applying their changes), before the PATH becomes active for _new processes_ started from Explorer or other process-starting applications, e.g. ConEmu.

If [`WM_SETTINGCHANGE`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange) is raised after changing the registry key, then Windows Explorer (amongst others) will refresh its cache of the env-vars, and hence new `cmd`, `powershell`, etc. windows will see the new path immediately.

At some point [Windows Terminal will also support handling this message](https://github.com/microsoft/terminal/issues/1125), and so new _tabs_ will see the updated `PATH`. [ConEmu already supports this for new tabs](https://github.com/Maximus5/ConEmu/issues/468#issuecomment-496038436), and Console2 is mentioned in a comment on that issue as supporting this. [ConsoleZ](https://documentation.help/ConsoleZ/settings_behavior.html) also supports `WM_SETTINGCHANGE`, but that can be disabled.

That Windows Terminal issue link also has a bunch of discussion of the low-level details of the Explorer and application-specific behaviour when receiving the message, but they're not super-important here, as the sender-side is [pretty close to](https://stackoverflow.com/a/63732690/166389):
```c++
SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, NULL, (LPARAM)TEXT("Environment"), SMTO_NORMAL, 1000, nullptr);
```

and poking around, there's some Python-implemented versions of this call at https://stackoverflow.com/q/21138014/166389.

**Comment by ofek** [comment]
Is the goal for updates to affect the current session, sort of like an automatic `source ~/.bashrc`?

**Comment by TBBle** [comment]
No, I don't think that's possible, unless the shell itself, e.g., cmd or PowerShell, also reacts to this message and refreshes its environment, which would require managing/merging any user-local changes to the values.

`setx`, for example, documents that it [does not affect the current session](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx). `set` in contrast is a built-in for CMD, and so _can_ change the current session's environment (but does not persist the changes).

**Comment by ofek** [comment]
Should be supported in https://pypi.org/project/userpath/1.8.0/

**Comment by TBBle** [comment]
Awesome. Tested okay in the context of pipx: https://github.com/pypa/pipx/issues/659#issuecomment-1025271187
